# -*- coding: utf-8 -*-
"""fizzbuzz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xIsI7O6QlJfBfJP4WsOtFaXlUZZeP32l
"""

liste = []
for i in range(100):
  if i % 3 == 0 :
    liste.append("fizz")
  elif i % 5 == 0:
    liste.append("buzz")
  elif i % 3 and i % 5 == 0:
    liste.append(fizzbuzz)
  else:
    liste.append(i)
print(liste)